project:
  title: "SSOQE - Reproducibility in Science"
  pre-render: "../R/00_Config_file.R"

format: 
  revealjs:
    slide-number: true
    theme: [default, custom_theme.scss]
    embed-resources: true
    preview-links: auto
    output-file: "index"
    output-ext: "html"
    include-in-header: "fonts-include.html"
    highlight-style: github-light